### ISSUE TITLE
Remove "Leave Course" from the Homepage

### ISSUE THREAD

**Issue by Blatzheim** [hpi-swt2/lecture-portal#240]
AC:
- [ ] The "Leave Course"-Button of a course should be removed from the Homepage

**Comment by essal0815** [comment]
@Blatzheim Are you sure you want to compleatly delete the button because there is also an issue (currently in CR) which renames it to "unenroll"
See issue #241

If deletion is wanted then the ticket probably needs soon a rework. But I guess unenroll is more useful, so I suggest to ignore this issue.

**Comment by Blatzheim** [comment]
You're right @essal0815. But #241 is about the button INSIDE the course vew, wether this issue is about the button in the home view.

I found it unnecessary to have that button in the home view, since you won't use it that often and the page would look a little cleaner then.

What do you think?
